# Generated by Django 6.0.7 on 2026-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedresume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
