# Generated by Django 6.0.7 on 2026-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_submittedresume_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedresume',
            name='ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittedresume',
            name='skill_gap',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
